apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"  # Deploy after Istio
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: "1.76.0"
    helm:
      values: |
        # External services configuration
        external_services:
          prometheus:
            url: "http://prometheus.monitoring:9090"
          grafana:
            enabled: true
            in_cluster_url: "http://grafana.monitoring:3000"
            url: "http://grafana.localhost"
          tracing:
            enabled: false  # Can enable later if you add Jaeger
        
        # Auth configuration (anonymous for local dev)
        auth:
          strategy: "anonymous"
        
        # Kiali configuration
        kiali_feature_flags:
          certificates_information_indicators:
            enabled: true
            secrets:
            - "cacerts"
            - "istio-ca-secret"
          clustering:
            enabled: true
          disabled_features: []
          validations:
            ignore: ["KIA1301"]
        
        # Server configuration
        server:
          web_root: "/"
          web_fqdn: "kiali.localhost"
          web_schema: "http"
        
        # Deployment configuration
        deployment:
          image_name: "quay.io/kiali/kiali"
          image_version: "v1.76.0"
          ingress:
            enabled: true
            class_name: "traefik"
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/router.entrypoints: web
          namespace: "istio-system"
          replicas: 1
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          
        # Installation configuration
        installation_tag: ""
        istio_namespace: "istio-system"
        
        # API configuration
        api:
          namespaces:
            exclude:
            - "kube-.*"
            - "openshift.*"
            - "ibm.*"
            - "kiali-operator"
            - "kong"
            include: []
            label_selector_exclude: ""
            label_selector_include: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true