apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: "1.27.2"
    helm:
      values: |
        pilot:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            EXTERNAL_ISTIOD: false
        global:
          meshID: mesh1
          multiCluster:
            clusterName: cluster1
          network: network1
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true