apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "37.1.2"
    helm:
      values: |
        image:
          tag: "v3.5"
          pullPolicy: IfNotPresent

        deployment:
          replicas: 1
        
        service:
          type: LoadBalancer
        
        ingressClass:
          enabled: true
          isDefaultClass: true
        
        ports:
          web:
            port: 8000
            expose:
              default: true
            exposedPort: 80
          websecure:
            port: 8443
            expose:
              default: true
            exposedPort: 443
        
        # Enable dashboard
        api:
          dashboard: true
          insecure: true
        
        # Configure providers - correct syntax for v37
        providers:
          kubernetesCRD:
            enabled: true
            allowExternalNameServices: false
          kubernetesIngress:
            enabled: true
            allowExternalNameServices: false
        
        # Logging
        logs:
          general:
            level: INFO
        
        # Metrics
        metrics:
          prometheus:
            service:
              enabled: true
        
        # Global configuration
        global:
          sendAnonymousUsage: false
        
        # Additional arguments
        additionalArguments:
          - "--log.level=INFO"
          - "--api.insecure=true"
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true