apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    # targetRevision: "25.0.0"
    helm:
      values: |
        deployment:
          replicas: 1
        service:
          type: LoadBalancer
        ingressClass:
          enabled: true
          isDefaultClass: true
        ports:
          web:
            port: 80
            expose: true
          websecure:
            port: 443
            expose: true
        api:
          dashboard: true
          insecure: true
        providers:
          kubernetesingress:
            ingressclass: traefik
          kubernetescrd:
            enabled: true
        logs:
          general:
            level: INFO
        metrics:
          prometheus:
            service:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true