apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: "2.10.2"
    helm:
      values: |
        # Loki configuration
        loki:
          enabled: true
          persistence:
            enabled: true
            storageClassName: longhorn
            size: 10Gi
          config:
            auth_enabled: false
            server:
              http_listen_port: 3100
            ingester:
              lifecycler:
                address: 127.0.0.1
                ring:
                  kvstore:
                    store: inmemory
                  replication_factor: 1
            schema_config:
              configs:
              - from: 2020-10-24
                store: boltdb-shipper
                object_store: filesystem
                schema: v11
                index:
                  prefix: index_
                  period: 24h
            storage_config:
              boltdb_shipper:
                active_index_directory: /loki/boltdb-shipper-active
                cache_location: /loki/boltdb-shipper-cache
                shared_store: filesystem
              filesystem:
                directory: /loki/chunks
            limits_config:
              enforce_metric_name: false
              reject_old_samples: true
              reject_old_samples_max_age: 168h
            chunk_store_config:
              max_look_back_period: 0s
            table_manager:
              retention_deletes_enabled: false
              retention_period: 0s
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        
        # Promtail configuration
        promtail:
          enabled: true
          config:
            serverPort: 3101
            clients:
            - url: http://loki-stack:3100/loki/api/v1/push
            scrapeConfigs:
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
              - role: pod
              pipeline_stages:
              - cri: {}
              relabel_configs:
              - source_labels: [__meta_kubernetes_pod_controller_name]
                regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                target_label: __tmp_controller_name
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_label_app, __tmp_controller_name, __meta_kubernetes_pod_name]
                regex: ^;*([^;]+)(;.*)?$
                target_label: app
                replacement: $1
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component, __meta_kubernetes_pod_label_component]
                regex: ^;*([^;]+)(;.*)?$
                target_label: component
                replacement: $1
              - action: replace
                source_labels: [__meta_kubernetes_pod_node_name]
                target_label: node_name
              - action: replace
                source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - action: replace
                replacement: $1
                separator: /
                source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_name]
                target_label: job
              - action: replace
                source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - action: replace
                source_labels: [__meta_kubernetes_pod_container_name]
                target_label: container
              - action: replace
                replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
                target_label: __path__
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
        
        # Fluent Bit (alternative to Promtail)
        fluent-bit:
          enabled: false
        
        # Grafana integration (disable since we have it in monitoring)
        grafana:
          enabled: false
        
        # Prometheus integration
        prometheus:
          enabled: false
        
        # File browser
        filebeat:
          enabled: false
        
        # Log gateway
        logstash:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true