apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/k8s-bootstrap-poc
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
      exclude: "app-of-apps.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true